### ISSUE TITLE
Windows 10 crash report

### ISSUE THREAD

**Issue by Stvduong** [openhardwaremonitor/openhardwaremonitor#1035]
Hello,

Recently encountered this error. Windows 10 recently reinstalled and this pop up a few days after. Thank you in advance for any advice given.

Version: 0.8.0.0

System.ArgumentException: Value does not fall within the expected range.
   at OpenHardwareMonitor.TaskScheduler.TaskSchedulerClass.GetRunningTasks(Int32 flags)
   at OpenHardwareMonitor.GUI.StartupManager..ctor()
   at OpenHardwareMonitor.GUI.MainForm..ctor()
   at OpenHardwareMonitor.Program.Main()

Common Language Runtime: 4.0.30319.42000
Operating System: Microsoft Windows NT 10.0.15063.0
Process Type: 64-Bit

**Comment by moellerm** [comment]
This should be fixed in version 0.9.1.
