### ISSUE TITLE
Webserver returning JS error: ": viewModel is not defined"

### ISSUE THREAD

**Issue by seanvree** [openhardwaremonitor/openhardwaremonitor#1080]
OS: Windows 10E 1709 FCU

ISSUE: webserver not populating data. 

Had this working for a year or two, not sure why this is happening now.

In addition, when I click on options -> remote web server -> PORT -> the app crashes with the error below:

```
Version: 0.8.0.3

System.ArgumentOutOfRangeException: Value of '8050' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at OpenHardwareMonitor.GUI.PortForm.PortForm_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

However, when the app is first launched, the webserver is running on port 8065, but not serving data, the browser console returns these errors:

```
ohm_web.js:103 Uncaught ReferenceError: viewModel is not defined
    at HTMLDivElement.slide (http://localhost:8050/js/ohm_web.js:103:7)
    at b.(anonymous function).(anonymous function)._trigger (http://localhost:8050/js/jquery-ui-1.8.16.custom.min.js:33:438)
    at b.(anonymous function).(anonymous function)._slide (http://localhost:8050/js/jquery-ui-1.8.16.custom.min.js:102:453)
    at b.(anonymous function).(anonymous function)._mouseDrag (http://localhost:8050/js/jquery-ui-1.8.16.custom.min.js:100:54)
    at b.(anonymous function).(anonymous function)._mouseMove (http://localhost:8050/js/jquery-ui-1.8.16.custom.min.js:49:92)
    at HTMLDocument._mouseMoveDelegate (http://localhost:8050/js/jquery-ui-1.8.16.custom.min.js:48:252)
    at HTMLDocument.dispatch (http://localhost:8050/js/jquery-1.7.2.min.js:3:4816)
    at HTMLDocument.i (http://localhost:8050/js/jquery-1.7.2.min.js:3:709)

```

![image](https://user-images.githubusercontent.com/8906637/36154341-f2940832-1085-11e8-8f93-8bab60389468.png)

**Comment by DarthDestroyer** [comment]
So, i tested it.

* I can change the Port to whatever Integer i want (btw: after Port change, restart the Webserver)
* I can run the webserver as it should

I think, that there is an error in the returning data!
Could you Post the "Response" Content from "/data.json" here?
(You posted Screenshots from the Dev-Tools, so i think you could find it?!)

Maybe, the fault is missing Hardware Support... A Report of your Configuration could help us, too!

**Comment by seanvree** [comment]
@DarthDestroyer  

here's the response content:
```
{"id": 0, "Text": "Sensor", "Children": [{"id": 1, "Text": "VREEPLEXDESKTOP", "Children": [{"id": 2, "Text": "Gigabyte H170N-WIFI-CF", "Children": [{"id": 3, "Text": "ITE IT8628E", "Children": [{"id": 4, "Text": "Voltages", "Children": [{"id": 5, "Text": "Voltage #1", "Children": [], "Min": "0.084 V", "Value": "0.924 V", "Max": "1.320 V", "ImageURL": "images/transparent.png"}, {"id": 6, "Text": "Voltage #2", "Children": [], "Min": "2.016 V", "Value": "2.028 V", "Max": "2.028 V", "ImageURL": "images/transparent.png"}, {"id": 7, "Text": "Voltage #3", "Children": [], "Min": "2.004 V", "Value": "2.016 V", "Max": "2.016 V", "ImageURL": "images/transparent.png"}, {"id": 8, "Text": "Voltage #4", "Children": [], "Min": "2.004 V", "Value": "2.016 V", "Max": "2.016 V", "ImageURL": "images/transparent.png"}, {"id": 9, "Text": "Voltage #5", "Children": [], "Min": "0.012 V", "Value": "0.012 V", "Max": "1.152 V", "ImageURL": "images/transparent.png"}, {"id": 10, "Text": "Voltage #6", "Children": [], "Min": "1.080 V", "Value": "1.080 V", "Max": "1.080 V", "ImageURL": "images/transparent.png"}, {"id": 11, "Text": "Voltage #7", "Children": [], "Min": "1.200 V", "Value": "1.200 V", "Max": "1.200 V", "ImageURL": "images/transparent.png"}, {"id": 12, "Text": "Standby +3.3V", "Children": [], "Min": "3.384 V", "Value": "3.384 V", "Max": "3.384 V", "ImageURL": "images/transparent.png"}, {"id": 13, "Text": "VBat", "Children": [], "Min": "2.808 V", "Value": "2.808 V", "Max": "2.808 V", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/voltage.png"}, {"id": 14, "Text": "Temperatures", "Children": [{"id": 15, "Text": "Temperature #1", "Children": [], "Min": "87.8 °F", "Value": "93.2 °F", "Max": "104.0 °F", "ImageURL": "images/transparent.png"}, {"id": 16, "Text": "MB Temp", "Children": [], "Min": "102.2 °F", "Value": "107.6 °F", "Max": "118.4 °F", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/temperature.png"}, {"id": 17, "Text": "Fans", "Children": [{"id": 18, "Text": "Fan #1", "Children": [], "Min": "1395 RPM", "Value": "1421 RPM", "Max": "1452 RPM", "ImageURL": "images/transparent.png"}, {"id": 19, "Text": "Fan #2", "Children": [], "Min": "1790 RPM", "Value": "1819 RPM", "Max": "1844 RPM", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/fan.png"}, {"id": 20, "Text": "Controls", "Children": [{"id": 21, "Text": "Fan Control #1", "Children": [], "Min": "-", "Value": "-", "Max": "-", "ImageURL": "images/transparent.png"}, {"id": 22, "Text": "Fan Control #2", "Children": [], "Min": "-", "Value": "-", "Max": "-", "ImageURL": "images/transparent.png"}, {"id": 23, "Text": "Fan Control #3", "Children": [], "Min": "-", "Value": "-", "Max": "-", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/control.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/chip.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/mainboard.png"}, {"id": 24, "Text": "Intel Core i7-6700K", "Children": [{"id": 25, "Text": "Clocks", "Children": [{"id": 26, "Text": "Bus Speed", "Children": [], "Min": "100 MHz", "Value": "100 MHz", "Max": "100 MHz", "ImageURL": "images/transparent.png"}, {"id": 27, "Text": "CPU Core #1", "Children": [], "Min": "802 MHz", "Value": "4008 MHz", "Max": "4208 MHz", "ImageURL": "images/transparent.png"}, {"id": 28, "Text": "CPU Core #2", "Children": [], "Min": "802 MHz", "Value": "4008 MHz", "Max": "4208 MHz", "ImageURL": "images/transparent.png"}, {"id": 29, "Text": "CPU Core #3", "Children": [], "Min": "802 MHz", "Value": "4008 MHz", "Max": "4208 MHz", "ImageURL": "images/transparent.png"}, {"id": 30, "Text": "CPU Core #4", "Children": [], "Min": "802 MHz", "Value": "4008 MHz", "Max": "4208 MHz", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/clock.png"}, {"id": 31, "Text": "Temperatures", "Children": [{"id": 32, "Text": "CPU Core #1", "Children": [], "Min": "66.2 °F", "Value": "77.0 °F", "Max": "149.0 °F", "ImageURL": "images/transparent.png"}, {"id": 33, "Text": "CPU Core #2", "Children": [], "Min": "66.2 °F", "Value": "78.8 °F", "Max": "150.8 °F", "ImageURL": "images/transparent.png"}, {"id": 34, "Text": "CPU Core #3", "Children": [], "Min": "66.2 °F", "Value": "75.2 °F", "Max": "136.4 °F", "ImageURL": "images/transparent.png"}, {"id": 35, "Text": "CPU Core #4", "Children": [], "Min": "64.4 °F", "Value": "73.4 °F", "Max": "140.0 °F", "ImageURL": "images/transparent.png"}, {"id": 36, "Text": "CPU Package", "Children": [], "Min": "75.2 °F", "Value": "84.2 °F", "Max": "150.8 °F", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/temperature.png"}, {"id": 37, "Text": "Load", "Children": [{"id": 38, "Text": "CPU Total", "Children": [], "Min": "2.3 %", "Value": "20.1 %", "Max": "96.6 %", "ImageURL": "images/transparent.png"}, {"id": 39, "Text": "CPU Core #1", "Children": [], "Min": "3.1 %", "Value": "21.4 %", "Max": "100.0 %", "ImageURL": "images/transparent.png"}, {"id": 40, "Text": "CPU Core #2", "Children": [], "Min": "1.4 %", "Value": "19.9 %", "Max": "97.3 %", "ImageURL": "images/transparent.png"}, {"id": 41, "Text": "CPU Core #3", "Children": [], "Min": "1.5 %", "Value": "17.7 %", "Max": "95.5 %", "ImageURL": "images/transparent.png"}, {"id": 42, "Text": "CPU Core #4", "Children": [], "Min": "1.7 %", "Value": "21.3 %", "Max": "97.0 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}, {"id": 43, "Text": "Powers", "Children": [{"id": 44, "Text": "CPU Package", "Children": [], "Min": "18.1 W", "Value": "35.1 W", "Max": "78.9 W", "ImageURL": "images/transparent.png"}, {"id": 45, "Text": "CPU Cores", "Children": [], "Min": "6.9 W", "Value": "23.3 W", "Max": "66.2 W", "ImageURL": "images/transparent.png"}, {"id": 46, "Text": "CPU Graphics", "Children": [], "Min": "0.0 W", "Value": "0.3 W", "Max": "5.5 W", "ImageURL": "images/transparent.png"}, {"id": 47, "Text": "CPU DRAM", "Children": [], "Min": "1.0 W", "Value": "1.8 W", "Max": "3.4 W", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/power.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/cpu.png"}, {"id": 48, "Text": "Generic Memory", "Children": [{"id": 49, "Text": "Load", "Children": [{"id": 50, "Text": "Memory", "Children": [], "Min": "34.0 %", "Value": "40.8 %", "Max": "61.3 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}, {"id": 51, "Text": "Data", "Children": [{"id": 52, "Text": "Used Memory", "Children": [], "Min": "10.5 GB", "Value": "12.6 GB", "Max": "19.0 GB", "ImageURL": "images/transparent.png"}, {"id": 53, "Text": "Available Memory", "Children": [], "Min": "12.0 GB", "Value": "18.3 GB", "Max": "20.4 GB", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/power.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/ram.png"}, {"id": 54, "Text": "NVIDIA GeForce GT 620", "Children": [{"id": 55, "Text": "Clocks", "Children": [{"id": 56, "Text": "GPU Core", "Children": [], "Min": "405 MHz", "Value": "405 MHz", "Max": "700 MHz", "ImageURL": "images/transparent.png"}, {"id": 57, "Text": "GPU Memory", "Children": [], "Min": "324 MHz", "Value": "324 MHz", "Max": "500 MHz", "ImageURL": "images/transparent.png"}, {"id": 58, "Text": "GPU Shader", "Children": [], "Min": "810 MHz", "Value": "810 MHz", "Max": "1399 MHz", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/clock.png"}, {"id": 59, "Text": "Temperatures", "Children": [{"id": 60, "Text": "GPU Core", "Children": [], "Min": "80.6 °F", "Value": "87.8 °F", "Max": "95.0 °F", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/temperature.png"}, {"id": 61, "Text": "Load", "Children": [{"id": 62, "Text": "GPU Core", "Children": [], "Min": "0.0 %", "Value": "0.0 %", "Max": "0.0 %", "ImageURL": "images/transparent.png"}, {"id": 63, "Text": "GPU Memory Controller", "Children": [], "Min": "0.0 %", "Value": "0.0 %", "Max": "0.0 %", "ImageURL": "images/transparent.png"}, {"id": 64, "Text": "GPU Video Engine", "Children": [], "Min": "0.0 %", "Value": "0.0 %", "Max": "0.0 %", "ImageURL": "images/transparent.png"}, {"id": 65, "Text": "GPU Memory", "Children": [], "Min": "2.8 %", "Value": "2.8 %", "Max": "2.8 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}, {"id": 66, "Text": "Controls", "Children": [{"id": 67, "Text": "GPU Fan", "Children": [], "Min": "52.0 %", "Value": "52.0 %", "Max": "52.0 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/control.png"}, {"id": 68, "Text": "Data", "Children": [{"id": 69, "Text": "GPU Memory Free", "Children": [], "Min": "1989.9 MB", "Value": "1990.1 MB", "Max": "1990.1 MB", "ImageURL": "images/transparent.png"}, {"id": 70, "Text": "GPU Memory Used", "Children": [], "Min": "57.9 MB", "Value": "57.9 MB", "Max": "58.1 MB", "ImageURL": "images/transparent.png"}, {"id": 71, "Text": "GPU Memory Total", "Children": [], "Min": "2048.0 MB", "Value": "2048.0 MB", "Max": "2048.0 MB", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/power.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/nvidia.png"}, {"id": 72, "Text": "S=#1ÚcqT", "Children": [{"id": 73, "Text": "Load", "Children": [{"id": 74, "Text": "Used Space", "Children": [], "Min": "57.8 %", "Value": "57.8 %", "Max": "57.8 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 75, "Text": "Generic Hard Disk", "Children": [{"id": 76, "Text": "Load", "Children": [{"id": 77, "Text": "Used Space", "Children": [], "Min": "93.4 %", "Value": "94.7 %", "Max": "97.3 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 78, "Text": "Generic Hard Disk", "Children": [{"id": 79, "Text": "Load", "Children": [{"id": 80, "Text": "Used Space", "Children": [], "Min": "97.5 %", "Value": "97.9 %", "Max": "98.0 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 81, "Text": "Generic Hard Disk", "Children": [{"id": 82, "Text": "Load", "Children": [{"id": 83, "Text": "Used Space", "Children": [], "Min": "97.5 %", "Value": "97.9 %", "Max": "98.0 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 84, "Text": "F: WDC WD80 PUZX-64NEAY0", "Children": [{"id": 85, "Text": "Load", "Children": [{"id": 86, "Text": "Used Space", "Children": [], "Min": "98.0 %", "Value": "98.5 %", "Max": "98.5 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 87, "Text": "Generic Hard Disk", "Children": [{"id": 88, "Text": "Load", "Children": [{"id": 89, "Text": "Used Space", "Children": [], "Min": "97.6 %", "Value": "97.9 %", "Max": "97.9 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 90, "Text": "WDC WD40E31X-00HY4A0", "Children": [{"id": 91, "Text": "Temperatures", "Children": [{"id": 92, "Text": "Temperature", "Children": [], "Min": "82.4 °F", "Value": "84.2 °F", "Max": "96.8 °F", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/temperature.png"}, {"id": 93, "Text": "Load", "Children": [{"id": 94, "Text": "Used Space", "Children": [], "Min": "92.4 %", "Value": "93.8 %", "Max": "93.8 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 95, "Text": "Samsung SSD 850 EVO 1TB", "Children": [{"id": 96, "Text": "Temperatures", "Children": [{"id": 97, "Text": "Temperature", "Children": [], "Min": "84.2 °F", "Value": "87.8 °F", "Max": "105.8 °F", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/temperature.png"}, {"id": 98, "Text": "Load", "Children": [{"id": 99, "Text": "Used Space", "Children": [], "Min": "65.1 %", "Value": "68.4 %", "Max": "70.2 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}, {"id": 100, "Text": "Data", "Children": [{"id": 101, "Text": "Total Bytes Written", "Children": [], "Min": "238530.0 GB", "Value": "239355.4 GB", "Max": "239355.4 GB", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/power.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}, {"id": 102, "Text": "WDC WD1001FALS-00J7B1", "Children": [{"id": 103, "Text": "Temperatures", "Children": [{"id": 104, "Text": "Temperature", "Children": [], "Min": "95.0 °F", "Value": "98.6 °F", "Max": "105.8 °F", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/temperature.png"}, {"id": 105, "Text": "Load", "Children": [{"id": 106, "Text": "Used Space", "Children": [], "Min": "94.5 %", "Value": "94.5 %", "Max": "94.5 %", "ImageURL": "images/transparent.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/load.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/hdd.png"}], "Min": "", "Value": "", "Max": "", "ImageURL": "images_icon/computer.png"}], "Min": "Min", "Value": "Value", "Max": "Max", "ImageURL": ""}
```

I wasn't sure how to create a "configuration report", but here is the output "save report"

https://gist.github.com/seanvree/13f92db466bef85514a85509c2510993

**Comment by DarthDestroyer** [comment]
Could you try to rename GenericHarddisk?

Drive name: mÑÂÂõÿÿ

**Comment by seanvree** [comment]
@DarthDestroyer  yup, that did it. Thanks.
